{
 "title": "06 - DNS UNBOUND",
 "tags": [
  "unbound",
  "dns",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(unbound_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Consultas",
   "type": "stat",
   "description": "Número total de consultas recebidas no intervalo de tempo selecionado.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_queries_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Consultas indesejadas",
   "type": "stat",
   "description": "Número total de consultas que foram recusadas ou descartadas porque falharam nas configurações de controle de acesso no intervalo de tempo selecionado.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_unwanted_queries_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Consultas por segundo",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(unbound_queries_total{instance=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Respostas indesejadas",
   "type": "stat",
   "description": "Número total de respostas indesejadas ou não solicitadas no intervalo de tempo selecionado. Um aumento acentuado no tráfego indesejado indica uma possível execução de falsificação em andamento.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_unwanted_replies_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Tamanho do cache de memória",
   "type": "stat",
   "description": "Memória máxima em uso pelos caches no intervalo de tempo selecionado",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(unbound_memory_caches_bytes{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "The number of threads created to serve clients",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_num_threads{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Tempo de resposta",
   "type": "heatmap",
   "description": "Tempo de resposta da consulta em segundos",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(unbound_response_time_seconds_bucket{instance=\"$instance\", le=~\"0.001024|0.002048|0.004096|0.008192|0.016384|0.032768|0.065536|0.131072|0.262144|0.524288|1|2|4|8|16|32|64\"}[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Proporção de acertos/erros de cache",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_cache_hits_total{instance=\"$instance\"}[$__range]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(increase(unbound_cache_misses_total{instance=\"$instance\"}[$__range]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Consultas TCP recebidas",
   "type": "stat",
   "description": "Total number of queries that were made using TCP towards the Unbound server at the selected time range.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_tcp_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Consultas TCP de saída",
   "type": "stat",
   "description": "Total number of queries that were made using TCP towards the Unbound server  at the selected time range.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_tcp_out_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Taxa de consultas limitadas",
   "type": "stat",
   "description": "Total number of queries that had been rate limited at the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_ratelimited_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Consultas TLS recebidas",
   "type": "stat",
   "description": "Total number of queries that were made using TLS towards the Unbound server at the selected time range.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_tls_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Consultas de retomada de TLS",
   "type": "stat",
   "description": "Total number of queries that were made using TLS resumption at the selected time range.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_tls_resume_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Consultas IPv6",
   "type": "stat",
   "description": "Total number of queries that were made using IPv6 towards the Unbound server at the selected time range.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_ipv6_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Respostas seguras",
   "type": "stat",
   "description": "Total amount of answers that were secure (AD) at the selected time range.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_answers_secure_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Respostas falsas",
   "type": "stat",
   "description": "Total amount of answers that were bogus (withheld as SERVFAIL) at the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_answers_bogus_total{instance=\"$instance\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Consultas EDNS OPT",
   "type": "stat",
   "description": "Total number of queries that had an EDNS OPT record present at the selected time range.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_edns_present_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Consultas EDNS OPT + DNSSEC OK",
   "type": "stat",
   "description": "Total number of queries that had an EDNS OPT record with the DO (DNSSEC OK) bit set present at the selected time range.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(unbound_query_edns_DO_total{instance=\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Total de consultas por tipo",
   "type": "timeseries",
   "description": "Número total de consultas com um determinado tipo de consulta",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(unbound_query_types_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total de respostas por rcode",
   "type": "timeseries",
   "description": "Total number of answers by rcode",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(unbound_answer_rcodes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{rcode}}"
    },
    {
     "expr": "rate(unbound_answers_secure_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Secure (AD)"
    },
    {
     "expr": "rate(unbound_answers_bogus_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Bogus (SERVFAIL)"
    },
    {
     "expr": "rate(unbound_rrset_bogus_total{instance=\"$instance\"}[5m])",
     "legendFormat": "RRset bogus"
    }
   ]
  },
  {
   "title": "Total de consultas por sinalizador",
   "type": "timeseries",
   "description": "Total number of queries that had a given flag set in the header",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(unbound_query_flags_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{flag}}"
    },
    {
     "expr": "rate(unbound_query_edns_present_total{instance=\"$instance\"}[1m])",
     "legendFormat": "EDNS OPT"
    },
    {
     "expr": "rate(unbound_query_edns_DO_total{instance=\"$instance\"}[1m])",
     "legendFormat": "DO (DNSSEC OK)"
    }
   ]
  },
  {
   "title": "Total de consultas por opcode",
   "type": "timeseries",
   "description": "Total number of queries with a given query opcode",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(unbound_query_opcodes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{opcode}}"
    }
   ]
  },
  {
   "title": "Total de consultas por turma",
   "type": "timeseries",
   "description": "Total number of queries with a given query class",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(unbound_query_classes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Per thread",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total de consultas por thread",
     "type": "timeseries",
     "description": "Total number of queries handled by each worker thread",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(unbound_queries_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{thread}}"
      }
     ]
    },
    {
     "title": "Total de pré-buscas de cache por thread",
     "type": "timeseries",
     "description": "Total number of cache prefetches performed",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(unbound_prefetches_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{thread}}"
      }
     ]
    },
    {
     "title": "Total replies with zero TTL by thread",
     "type": "timeseries",
     "description": "Total number of replies with ttl zero, because they served an expired cache entry.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(unbound_zero_ttl_responses_total{instance=\"$instance\"}[5m])",
       "legendFormat": "{{thread}}"
      }
     ]
    },
    {
     "title": "Total held TCP buffers by thread",
     "type": "timeseries",
     "description": "Number of the currently held TCP buffers for incoming connections",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(unbound_tcp_usage_current{instance=\"$instance\"}[5m])",
       "legendFormat": "{{thread}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request list",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Solicitar tamanho da lista",
     "type": "timeseries",
     "description": "Current size of the request list, including internally generated queries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(unbound_request_list_current_all{instance=\"$instance\"}[5m]))",
       "legendFormat": "all"
      },
      {
       "expr": "sum(rate(unbound_request_list_current_user{instance=\"$instance\"}[5m]))",
       "legendFormat": "user"
      }
     ]
    },
    {
     "title": "Total exceeded queries",
     "type": "timeseries",
     "description": "Number of queries that were dropped because the request list was full",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(request_list_exceeded_total{instance=\"$instance\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total overwritten queries",
     "type": "timeseries",
     "description": "Total number of requests in the request list that were overwritten by newer entries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(unbound_request_list_overwritten_total{instance=\"$instance\"}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "DNSCrypt",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total successful queries",
     "type": "timeseries",
     "description": "Total number of queries that were encrypted and successfully decapsulated by dnscrypt",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(unbound_dnscrypt_valid_queries_total{instance=\"$instance\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total certificate requesting queries",
     "type": "timeseries",
     "description": "Total number of queries that were requesting dnscrypt certificates",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(unbound_dnscrypt_cert_queries_total{instance=\"$instance\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total received cleartext queries",
     "type": "timeseries",
     "description": "Total number of queries received on dnscrypt port that were cleartext and not a request for certificates",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(unbound_dnscrypt_cleartext_queries_total{instance=\"$instance\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total malformed queries",
     "type": "timeseries",
     "description": "Total number of requests that were neither cleartext, not valid dnscrypt messages",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(unbound_dnscrypt_malformed_queries_total{instance=\"$instance\"}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cache hits / misses",
     "type": "timeseries",
     "description": "Hits: total number of queries that were successfully answered using a cache lookup.\n\nMisses: total number of cache queries that needed recursive processing",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(unbound_cache_hits_total{instance=\"$instance\"}[5m]))",
       "legendFormat": "hits"
      },
      {
       "expr": "sum(irate(unbound_cache_misses_total{instance=\"$instance\"}[5m]))",
       "legendFormat": "misses"
      }
     ]
    },
    {
     "title": "Cache size",
     "type": "timeseries",
     "description": "Memory in bytes by caches",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(unbound_memory_caches_bytes{instance=\"$instance\"}[5m])",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "Cached entries",
     "type": "timeseries",
     "description": "The number of cached entries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "unbound_cache_count_total{instance=\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Modules size",
     "type": "timeseries",
     "description": "Memory in use by modules",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "unbound_memory_modules_bytes", "legendFormat": "{{module}}" }
     ]
    },
    {
     "title": "Stream wait buffers size",
     "type": "timeseries",
     "description": " The number of bytes in the stream wait buffers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(unbound_memory_stream_wait_count{instance=\"$instance\"}[5m])"
      }
     ]
    }
   ]
  }
 ]
}